package <%= groupName %>;

import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.MatcherAssert.assertThat;

/*
	Generated by Bancey's Yeoman Spigot Generator
*/
public class MainTest {
	
	@Test
	public void test_on_enable() {
		throw NotYetImplementedException();
	}
}